version: "3.9"

services:

  parkify-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: parkify-sql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - parkifynet

  parkify-rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: parkify-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - parkifynet

  parkify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parkify-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=parkify-sql,1433;Database=ParkifyDB;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
      - RabbitMQ__Host=parkify-rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
    ports:
      - "5050:5050"
    depends_on:
      - parkify-sql
      - parkify-rabbitmq
    networks:
      - parkifynet

networks:
  parkifynet:
    driver: bridge