services:

  parkify-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: parkify-sql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - parkifynet

  parkify-rabbitmq:
    image: rabbitmq:3.12.1-management
    container_name: parkify-rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - parkifynet

  parkify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: parkify-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - ConnectionStrings__DefaultConnection=Server=parkify-sql,1433;Database=${SQL_DATABASE};User=sa;Password=${SQL_PASSWORD};TrustServerCertificate=True;

      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}

      - Stripe__SecretKey=${STRIPE_SECRET}
      - Stripe__PublishableKey=${STRIPE_PUBLISHABLE}

      - RabbitMQ__Host=parkify-rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=${RABBIT_USER}
      - RabbitMQ__Password=${RABBIT_PASS}
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__NotificationQueue=parkify.notifications
      - RabbitMQ__ExchangeName=parkify.exchange

      - Smtp__Host=${SMTP_HOST}
      - Smtp__Port=${SMTP_PORT}
      - Smtp__Username=${SMTP_USERNAME}
      - Smtp__Password=${SMTP_PASSWORD}
      - Smtp__EnableSsl=true
      - Smtp__FromAddress=${SMTP_FROM}
      - Smtp__FromName=${SMTP_NAME}

    ports:
      - "5050:5050"
    depends_on:
      - parkify-sql
      - parkify-rabbitmq
    networks:
      - parkifynet

networks:
  parkifynet:
    driver: bridge